apiVersion: v1
kind: ConfigMap
metadata:
  name: sample-config-dev
data:
  PORT: '3000'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
      - name: callmon-container
        image: {{ .Values.image.repository }}/sample:{{ .Values.image.tag }}
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: sample-config-dev
      imagePullSecrets:
      - name: {{ .Values.imagePullSecrets }}